import type { Metadata } from "next";
import Navbar from "@/components/navbar2";
import { twJoin } from "tailwind-merge";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="">
      <Navbar />
      {children}
    </main>
  );
}
