export default function Head() {
  // On page load or when changing themes, best to add inline in `head` to avoid FOUC

  return (
    <>
      <title>Hackrnews</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
