import type { Metadata } from "next";
import { twJoin } from "tailwind-merge";
import "./globals.css";
import SystemThemeLoader from "./system-theme-loader";
import { josefinSans } from "@/utils/fonts";
import Navbar from "../components/navbar";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  const theme = cookies().get("theme")?.value ?? "system";

  return (
    <html lang="en" className={theme}>
      <body
        className={twJoin(
          "bg-background transition-colors p-2 mx-auto md:p-4 text-textColor container max-w-6xl",
          josefinSans.className,
        )}
      >
        <SystemThemeLoader theme={theme} />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
