import type { Metadata } from "next";
import { twJoin } from "tailwind-merge";
import "./globals.css";
import ThemeLoader from "./theme-loader";
import { josefinSans } from "@/utils/fonts";
import Navbar from "../components/navbar";
import { cookies } from "next/headers";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
		modal: React.ReactNode;
}) {
	const theme = getThemeCookie();

	return (
		<html
			data-mode={theme ?? "system"}
			lang="en"
			className={theme === "dark" ? "dark" : ""}
		>
			<body
				className={twJoin(
					"bg-background transition-colors p-2 mx-auto md:p-4 text-textColor container",
					josefinSans.className,
					// TODO: add dark and light colors
				)}
			>
				<ThemeLoader />
				<Navbar />
				{children}
			</body>
		</html>
	);
}

function getThemeCookie(): string {
	const cookie = cookies().get("theme");
	if (cookie) {
		return cookie.value;
	}

	return "system";
}
