import type { Metadata } from "next";
import "./globals.css";
import { twJoin } from "tailwind-merge";
import { josefinSans } from "@/ui/fonts";
import Navbar from "@/components/navbar";
import { handleThemeCookie } from "./theme-cookie";
import Script from "next/script";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const theme = handleThemeCookie()

    return (
        <html lang="en" className={theme}>

            <Script id="theme-switcher">
                {`
                    function getCookie(name) {
                        var cookies = document.cookie.split(';');
                        for (var i = 0; i < cookies.length; i++) {
                            var cookie = cookies[i].trim();
                            if (cookie.indexOf(name + '=') === 0) {
                                return cookie.substring(name.length + 1);
                            }
                        }
                        return null;
                    }

                    var theme = getCookie('theme');
                    console.log("theme: ", theme)
                    if (!theme || theme === 'system') {
                        if (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches) {
                            document.documentElement.className = "dark";
                                window.matchMedia("(prefers-color-scheme: dark)").addEventListener('change', (e) => {
                                    if (e.matches) {
                                        document.documentElement.className = "dark";
                                    } else {
                                        document.documentElement.className = "light";
                                    }
                                })
                        }
                    } 
                `}
            </Script>
            <body
                className={twJoin(
                    "bg-background p-2 mx-auto md:p-4 text-textColor container",
                    josefinSans.className,
                    // TODO: add dark and light colors
                )}
            >
                <Navbar />
                {/* <Sidebar className='hidden' /> */}
                {children}
            </body>
        </html>
    );
}

